Repository xenia-manager/Optimized-Settings, pull requests merged in 2024-10, with the labels that each got.

#1 Red Dead Redemption Optimized Settings
  Settings/5454082B.json
Labels: enhancement

#4 Optimal settings for more games
  Settings/454108EF.json
  Settings/4D5307D5.json
  Settings/4D53082D.json
  Settings/4D5308AB.json
  Settings/4D530910.json
  Settings/545107D1.json
  Settings/545107FC.json
Labels: enhancement, ready for merge

#6 More optimized settings
  Settings/45410813.json
  Settings/4541087F.json
  Settings/454108E6.json
  Settings/4D5307D1.json
  Settings/4D5307D3.json
  Settings/4D5307EA.json
  Settings/4D5307F1.json
  Settings/4D5307F9.json
  Settings/4D53084D.json
  Settings/4D53085B.json
  Settings/4D530877.json
  Settings/4D530919.json
  Settings/4D530A26.json
  Settings/4D530AA4.json
  Settings/534307F8.json
  Settings/545407EE.json
  Settings/545407F8.json
  Settings/555307F0.json
  Settings/55530833.json
  Settings/5553087E.json
  Settings/584111F7.json
Labels: enhancement, ready for merge

#7 Even more optimized settings
  Settings/415607E1.json
  Settings/41560914.json
  Settings/424107DC.json
  Settings/454107D9.json
  Settings/4541080F.json
  Settings/45410830.json
  Settings/454108D4.json
  Settings/4B4E080A.json
  Settings/4B4E0840.json
  Settings/4D5307DC.json
  Settings/4D5308BC.json
  Settings/4E4D07FC.json
  Settings/4E4D0826.json
  Settings/544307D1.json
  Settings/545107D8.json
  Settings/5451083B.json
  Settings/58410960.json
  Settings/5841125A.json
Labels: enhancement, needs review
